version: 2.1

orbs:
  architect: giantswarm/architect@6.7.0

workflows:
  build:
    jobs:
      - architect/go-build:
          name: go-build
          context: architect
          resource_class: large
          binary: dns-operator-azure
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          name: push-to-registries
          context: architect
          requires:
            - go-build
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          name: push-to-control-plane-catalog
          context: architect
          chart: dns-operator-azure
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          requires:
            - push-to-registries
          filters:
            branches:
              ignore:
                - main
                - master
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: push-to-capz-app-collection
          context: architect
          app_name: dns-operator-azure
          app_namespace: giantswarm
          app_collection_repo: capz-app-collection
          requires:
            - push-to-control-plane-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
