---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dns-operator-azure-role
rules:
- apiGroups:
  - cluster.x-k8s.io
  - infrastructure.cluster.x-k8s.io
  resources:
  - azureclusters
  - azureclusters/status
  - clusters
  - clusters/status
  verbs:
  - get
  - list
  - patch
  - update
  - watch
