apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
        {{- if .Values.azure.workloadIdentity.clientID }}
        azure.workload.identity/use: "true"
        {{- end }}
    spec:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
            weight: 10
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
        - /manager
        args:
        - --base-domain={{ .Values.baseDomain }}
        - --base-domain-resource-group={{ .Values.azure.baseDNSZone.resourceGroup }}
        - --zap-log-level=info
        - --metrics-addr=:8666
        - --management-cluster-name={{ .Values.managementCluster.name }}
        - --management-cluster-namespace={{ .Values.managementCluster.namespace }}
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: tenantID
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: subscriptionID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: clientID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: clientSecret
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        ports:
        - name: metrics
          containerPort: 8666
          protocol: TCP
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 250Mi
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
      - effect: NoSchedule
        key: "node.cluster.x-k8s.io/uninitialized"
        operator: "Exists"
