apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
        - /manager
        args:
        - --watch-filter={{ .Values.watchfilter }}
        - --base-domain={{ .Values.baseDomain }}
        - --base-zone-client-id={{ .Values.azure.baseDNSZone.clientID }}
        - --base-zone-client-secret={{ .Values.azure.baseDNSZone.clientSecret }}
        - --base-zone-subscription-id={{ .Values.azure.baseDNSZone.subscriptionID }}
        - --base-zone-tenant-id={{ .Values.azure.baseDNSZone.tenantID }}
        env:
        - name: AZURE_TENANT_ID
          value: {{ .Values.azure.cluster.tenantID }}
        - name: AZURE_SUBSCRIPTION_ID
          value: {{ .Values.azure.cluster.subscriptionID }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.azure.cluster.clientID }}
        - name: AZURE_CLIENT_SECRET
          value: {{ .Values.azure.cluster.clientSecret }}
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 250Mi
      terminationGracePeriodSeconds: 10
