apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
        - /manager
        args:
        - --watch-filter={{ .Values.watchfilter }}
        env:
        - name: MANAGEMENT_CLUSTER_NAME
          value: {{ .Values.managementCluster.name }}
        - name: MANAGEMENT_CLUSTER_AZURE_REGION
          value: {{ .Values.managementCluster.azure.region }}
        - name: AZURE_TENANT_ID
          value: {{ .Values.managementCluster.azure.credentials.tenantID }}
        - name: AZURE_SUBSCRIPTION_ID
          value: {{ .Values.managementCluster.azure.credentials.subscriptionID }}
        - name: AZURE_CLIENT_ID
          value: {{ .Values.managementCluster.azure.credentials.clientID }}
        - name: AZURE_CLIENT_SECRET
          value: {{ .Values.managementCluster.azure.credentials.clientSecret }}
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 250Mi
      terminationGracePeriodSeconds: 10
