apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "resource.default.name"  . }}
  namespace: {{ include "resource.default.namespace"  . }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        releaseRevision: {{ .Release.Revision | quote }}
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "resource.default.name"  . }}
      securityContext:
        runAsUser: {{ .Values.pod.user.id }}
        runAsGroup: {{ .Values.pod.group.id }}
      hostNetwork: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.registry.domain }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        command:
        - /manager
        args:
        - --base-domain={{ .Values.baseDomain }}
        - --base-domain-resource-group={{ .Values.azure.baseDNSZone.resourceGroup }}
        - --zap-log-level=info
        env:
        - name: AZURE_TENANT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: tenantID
        - name: AZURE_SUBSCRIPTION_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: subscriptionID
        - name: AZURE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: clientID
        - name: AZURE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ include "resource.default.name" . }}-azure-credentials
              key: clientSecret
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          requests:
            cpu: 50m
            memory: 150Mi
          limits:
            cpu: 250m
            memory: 250Mi
      terminationGracePeriodSeconds: 10
