apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}-azure-credentials
  namespace: {{ include "resource.default.namespace" . }}
data:
  tenantID: {{ .Values.azure.baseDNSZone.tenantID | b64enc | quote}}
  subscriptionID: {{ .Values.azure.baseDNSZone.subscriptionID | b64enc | quote}}
  clientID: {{ .Values.azure.baseDNSZone.clientID | b64enc | quote}}
  clientSecret: {{ .Values.azure.baseDNSZone.clientSecret | b64enc | quote}}
type: Opaque
